#!/bin/sh

mkdir -p opk
cp ./gambatte-dms-opendingux opk/gambatte-dms-opendingux
cp ./dist/gcw0/gambatte_dms.png opk/icon.png
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Gambatte DMS
Comment=GB/GBC emulator
Exec=gambatte-dms-opendingux %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk gambatte_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
